apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: {{ .Values.namespace }}
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: orky161/library-init:4
      {{- if or $.Values.deployment.env $.Values.deployment.envSecrets }}
      env:
        {{- range $key, $value := $.Values.deployment.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $secret := $.Values.deployment.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
          {{- end }}
         {{- end }}
