{{ if not $.Values.private }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Values.authService }}.{{ .Values.namespace }}.svc.cluster.local:80/api/auth/verify
    nginx.ingress.kubernetes.io/auth-snippet: |
        {{- range $paths := $.Values.public }}
        if ($request_uri {{ default "= " $paths.prefix }}/{{ $.Values.name }}{{ $paths.path }}) {
            set $req  {{ $paths.id }};
        }
        if ($request_method = {{ $paths.method }}) {
            set $req  "${req}{{ $paths.id }}";
        }
        if ($req = {{ $paths.id }}{{ $paths.id }}) {
            return 200;
        }
        {{- end }}

spec:
  rules:
      - http:
         paths:
            - backend:
                serviceName: {{ .Values.name }}-service
                servicePort: 80
              path: /{{ .Values.name }}(/|$)(.*)

{{ end }}
